personalSite/home/urls.py
from django.urls import path
from .views import * 

app_name = 'home'
urlpatterns = [
	path('',HomeView.as_view(),name='home'),
]

personalSite/personalSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from .views import *
from django.conf.urls import (handler400, handler403, handler404, handler500)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls'),name='project'),
    path('home/',include('home.urls'),name='home'),
    path('teaching/',include('teaching.urls'),name='teaching'),
    path('sandbox-1/',include('sandbox-1.urls'),name='sandbox-1'),
    path('',homeRedirect),
]

urlpatterns += staticfiles_urlpatterns()

personalSite/projects/urls.py
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [
	path('',views.ProjectListView.as_view(),name='list'),
	path('<int:pk>/',views.ProjectDetailView.as_view(),name='detail')
]

personalSite/teaching/urls.py
from django.urls import path
from .views import * 

app_name = 'teaching'
urlpatterns = [
	path('',TeachingView.as_view(),name='teaching'),
]

personalSite/home/models.py
from django.db import models
class Resume(models.Model):
	pdf = models.FileField(upload_to='personalSite/static')
	def __str__(self):
		return "Resume"

# Create your models here.

personalSite/personalSite/models.py
from django.db import models
class Resume(models.Model):
	pdf = models.FileField(upload_to='resume.pdf')

personalSite/projects/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
	name = models.CharField(max_length=50)
	source = models.URLField()
	summary = models.TextField()
	contents = models.TextField()
	def __str__(self):
		return self.name
	def getSummary(self):
		summary = self.contents[:97] + "..."
		return summary

personalSite/teaching/models.py
from django.db import models

# Create your models here.

personalSite/home/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.

class HomeView(generic.TemplateView):
	template_name = "home/home.html"

personalSite/personalSite/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.

from django.shortcuts import redirect
from django.http import HttpResponse

def homeRedirect(request):
	return redirect('home/')

personalSite/projects/views.py
from django.shortcuts import render
from django.views import generic
from .models import Project 
# Create your views here.

from django.http import HttpResponse

class ProjectListView(generic.ListView):
	template_name = 'projects/projects.html'
	context_object_name = 'project_list'
	def get_queryset(self):
		return Project.objects.order_by('-id').all()

class ProjectDetailView(generic.DetailView):
	model = Project
	template_name = 'projects/projectDetails.html'
	def get_queryset(self):
		return Project.objects.order_by('-id').all()
class HomeView(generic.TemplateView):
	template_name = 'home/home.html'

	

personalSite/teaching/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.
class TeachingView(generic.TemplateView):
	template_name = "teaching/teaching.html"

personalSite/home/templates/home/home.html
{% extends "personalSite/base.html" %}
{% block innerNav %}

	<li><a id="currentPage" href="{% url 'home:home' %}">Home</a></li>
	<li><a href="{% url 'teaching:teaching' %}">Teaching</a></li>
	<li><a href="{% url 'project:list' %}">Projects</a></li>
{% endblock %}

{% block content %}
	<h2>About</h2>
	<p>I am a junior computer science student currently attending Northwestern University, with experience as a TA at the Illinois Institute of Technology.</p>
	<p>In addition to pursuing my studies, I'm in the process of searching for a software development internship position for summer 2019. If you are looking for an intern with a solid foundation in computer science concepts (as well as a healthy passion for programming), <a href="mailto::zmckee@u.northwestern.edu">I'd love to hear from you.</a></p>
	<p>I have started attending my first hackathons in fall 2017 by attending <a href="https://mhacks.org/">MHacks X</a> and <a href="https://boilermake.org/home">Boilermake V</a> back-to-back. In spring 2018, I attended <a href="https://www.hackillinois.org/">HackIllinois.</a> I spent my time there developing my first RESTful API for a chrome extension. You can find specific details about the things I helped make at my <a href="https://devpost.com/ZacharyMcKee">Devpost profile.</a>, as well as the Projects section on this website.</p>
	<p>For my choice of programming languages, I have used a mix of Python, C, C#, Java, and LISP in the past. I'm comfortable with pretty much anything, though if I had to select a language I like writing in the most, it would probably be Python.</p>
	<p>I also have classroom experience with SQL (Oracle SQL and PostgreSQL).</p>
	<p>I use both Windows and Linux as operating systems of choice, depending on the task at hand -- if I'm doing a lot of programming work, I'll boot Ubuntu. If I want to take advantage of Microsoft's technologies (primarily for gaming), I'll switch to Windows.</p>
	<h2>Personal</h2>
	<p>I sometimes joke to myself that I was born with a keyboard in my hands. Since I was very little, computers have always fascinated me. The sheer complexity that goes into these machines is captivating -- if you have seen the schematics for any processor (such as the <a href=https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Intel_8008_arch.svg/1280px-Intel_8008_arch.svg.png>Intel 8008</a>), you know what I mean.</p>
	<p>In my free time, I enjoy PC gaming. Some old favorite titles of mine include Team Fortress 2, the Mass Effect series, and Simcity 4. </p>
	<p>Recently, I've also started to enjoy cooking -- it's somewhat similar to programming in that when you do either of these things, you start with a simple collection of entities (ingredients in cooking, language syntax and keywords in programming) that you put together to form a complex, rich final product.</p>
{% endblock %}

personalSite/personalSite/templates/error.html
<head>
	
	<link rel="stylesheet" href="/static/style.css">
	
	<link rel="shortcut icon" type="image/png" href="/static/favicon.png?v=2">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
	<title>Zachary R. McKee</title>
</head>
<div id="wrapper">
	<section id="main">
		{% block error %}
		{% endblock %}
		<h4>Please click <a href="#" onclick="history.go(-1)">here</a> to go to the previous page or <a href="{% url 'home:home' %}">here</a> to go back to the home page.</a><h4>
		<h5>If there is a problem with the site, please <a href="mailto:zmckee@hawk.iit.edu">contact me.</a></h5>
	</section>
	<footer>Zachary R. Mckee &copy; 2017-2018</footer>
</div>

personalSite/personalSite/templates/personalSite/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<link rel="stylesheet" href="{% static 'style.css' %}">
	{% load static %}
	<link rel="shortcut icon" type="image/png"  href="{% static 'favicon.png' %}?v=2">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu">
	<title>Zachary R. McKee</title>
	<meta name="google-site-verification" content="pp0_6fKJa7Gs2xg0nmbkSdIT08wj2tt52_morAUTpn8" />
	<meta name="google-site-verification" content="SK7i3ZrFP1V8ielOV_dF5hA_YCZmNRzj4DOSWxgiqms" />
</head>
<body>
	<div id="wrapper">
			
		<header>
			<h1>Zachary R. McKee</h1>
			<div id="about">
				<p>Former Teaching Assistant at Illinois Tech</p>
				<p>B.S. Computer Science -- 2020</p>
				<p>McCormick School of Engineering</p>
				<p>Northwestern University</p>
				<p><!-- Illinois Institute of Technology --></p>
				{% load static %}
				<p><a href="{% static 'resume13.pdf' %}">Resume</a></p>

			</div>
		</header>
		<nav>
			<ul id="externalNav">
				<li><a target= "_blank" href="https://www.linkedin.com/in/zacharyrmckee/">LinkedIn</a></li>
				<li><a target= "_blank" href="https://github.com/ZacharyRMcKee">GitHub</a></li>
				<li><a target= "_blank" href="https://devpost.com/ZacharyMcKee">Devpost</a></li>
				<li><p id="email">Email: zmckee@u.northwestern.edu</p></li>
			</ul>
		</nav>
		<div id="spacer"></div>
		<section id="main">
			<nav>
				<ul id="innerNav">
					{% block innerNav %}
					<li><a href="{% url 'home:home' %}">Home</a></li>
					<li><a href="teaching.html">Teaching</a></li>
					<li><a href="{% url 'project:list' %}">Projects</a></li>
					{% endblock %}
				</ul>

			</nav>

			{% block content %}
			{% endblock %}
		</section>
		<footer>Zachary R. McKee &copy; 2017-2018</footer>
	</div>
</body>
</html>

personalSite/projects/templates/projects/projectDetails.html
{% extends 'personalSite/base.html' %}

{% block innerNav %}

	<li><a href="{% url 'home:home' %}">Home</a></li>
	<li><a href="{% url 'teaching:teaching' %}">Teaching</a></li>
	<li><a href="" id="currentPage">Projects</a></li>
{% endblock %}
{% block content %}
	<h2>{{ project.name }}</h2>
	<p><a target= "_blank" href="{{ project.source}}">Source</a> | <a href="{% url 'project:list' %}">Back to Project List</a>
	<h3>Description</h3>
	<p>{{ project.summary|safe }}</p>
	{% if project.contents %}
		{{ project.contents|safe }}
	{% else %}
		<p>No detailed description available.</p>
	{% endif %}
{% endblock %}

personalSite/projects/templates/projects/projects.html
{% extends 'personalSite/base.html' %}


{% block innerNav %}

	<li><a href="{% url 'home:home' %}">Home</a></li>
	<li><a href="{% url 'teaching:teaching' %}">Teaching</a></li>
	<li><a id="currentPage" href="{% url 'project:list' %}">Projects</a></li>
{% endblock %}


{% block content %}	
	{% if project_list %}
		<hr/>
		{% for project in project_list %}
			<h2>{{ project.name }}</h2>
			<p><a target="_blank" href="{{ project.source }}">Source</a> | <a href={% url 'project:detail' project.id %}>Details</a></p>
			<h3>Description</h3>
			<p>{{ project.summary|safe }}</p>
			<hr/>
		{% endfor %}
	{% else %}
		<p>No projects are available.</p>
	{% endif %}
{% endblock %}

personalSite/teaching/templates/teaching/teaching.html
{% extends "personalSite/base.html" %}
{% block innerNav %}
	<li><a href="{% url 'home:home' %}">Home</a></li>
        <li><a id="currentPage" href="{% url 'teaching:teaching' %}">Teaching</a></li>
        <li><a href="{% url 'project:list' %}">Projects</a></li>
{% endblock %}

{% block content %}
	
	<p>Here is a list of courses i've worked for as a TA in the past.</p>
	<h2>Illinois Institute of Technology</h2>
	<hr/>
	<h3>CS 350 -- Spring 2018</h3>
	<h4>Taught by <a href="http://halek.co">Kyle C. Hale</a></h4>
	<h3>CS 350 -- Fall 2017</h3>
	<h4>Taught by <a href="http://www.cs.iit.edu/~sasaki/">Jim Sasaki</a></h4>

{% endblock %}